[versions]

assertj = '3.27.7'
jackson = '2.8.9'
junit = '6.1.3'
logback = '1.6.3'
slf4j = '2.0.18'
mockito = '5.23.0'

# --------------------------------------------------------------------------------
[libraries]

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-dataFormatYaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-dataTypeJdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
javaDiffUtils = "io.github.java-diff-utils:java-diff-utils:4.17"
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" } # BOM controls ver
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-engine  = { module = "org.junit.jupiter:junit-jupiter-engine" } # BOM controls ver
junit-launcher  = { module = "org.junit.platform:junit-platform-launcher" } # BOM controls ver
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
saxon = "net.sf.saxon:Saxon-HE:13.0"
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-log4jOverSlf4j = { module = "org.slf4j:log4j-over-slf4j", version.ref = "slf4j" }


# --------------------------------------------------------------------------------
[bundles]

basicTest-impl = [
  "assertj-core",
  "junit-api",
]

basicTest-runtime = [
  "junit-engine",
  "junit-launcher",
]

jackson = [
  "jackson.core",
  "jackson.annotations",
  "jackson.dataFormatYaml",
  "jackson.dataTypeJdk8",
  "jackson.databind",
]

# --------------------------------------------------------------------------------
[plugins]

shadow = { id = "com.gradleup.shadow", version = "9.6.1" }
analyze = { id = "ca.cutterslade.analyze", version = "2.0.0" }
